// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbGHK-RWW3Aqd7lH957TKWDO8feXdEjo',
    appId: '1:676380748472:web:9e0a33d4ef81e6205ae24d',
    messagingSenderId: '676380748472',
    projectId: 'citymap-122b1',
    authDomain: 'citymap-122b1.firebaseapp.com',
    storageBucket: 'citymap-122b1.appspot.com',
    measurementId: 'G-35BT5N2CDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq9SxVHaeu7Lo1bHnoVo_z4jcqVMkiUx0',
    appId: '1:676380748472:android:3759d2ddeab528685ae24d',
    messagingSenderId: '676380748472',
    projectId: 'citymap-122b1',
    storageBucket: 'citymap-122b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZz7eUcBO3DaL95bkCH0zVHsQNiNggQ0',
    appId: '1:676380748472:ios:5e2fcb96c63948085ae24d',
    messagingSenderId: '676380748472',
    projectId: 'citymap-122b1',
    storageBucket: 'citymap-122b1.appspot.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZz7eUcBO3DaL95bkCH0zVHsQNiNggQ0',
    appId: '1:676380748472:ios:5e2fcb96c63948085ae24d',
    messagingSenderId: '676380748472',
    projectId: 'citymap-122b1',
    storageBucket: 'citymap-122b1.appspot.com',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvbGHK-RWW3Aqd7lH957TKWDO8feXdEjo',
    appId: '1:676380748472:web:d10524e6f75ad8cd5ae24d',
    messagingSenderId: '676380748472',
    projectId: 'citymap-122b1',
    authDomain: 'citymap-122b1.firebaseapp.com',
    storageBucket: 'citymap-122b1.appspot.com',
    measurementId: 'G-TEBQ5TPZXH',
  );

}